### ISSUE TITLE
Add callback timing information

### ISSUE THREAD

**Issue by odow** [lanl-ansi/rosetta-opf#10]
Per an email with @ccoffrin 

> You are correct that 20% overall improvement represents a bigger improvement (often around 2x more) on just the derivative computations. To get a better handle on this, instead of switching to HSL, is there a way we can add derivative callback time tracking into the information that is reported in the rosetta-opf scripts?

**Comment by frapac** [comment]
I agree that we should report the time spent in the callbacks (apparently the latest Ipopt version does not report that information anymore). On my side, I am using the following fields in JuMP:
https://github.com/jump-dev/JuMP.jl/blob/master/src/nlp.jl#L359-L364

knowing that JuMP: 
- (1) first run a forward and a reverse passes to evaluate the objective, the constraints, the gradient and the Jacobian 
- (2) then evaluate the Hessian of the Lagrangian apart with a forward-over-reverse pass. 

Hence, if we exclude the time spent in the extraction, we know only the time spent in (1) (objective+gradient+constraint+Jacobian) and in (2) (Hessian). At least as far as I understand JuMP's AD.

**Comment by odow** [comment]
See https://github.com/lanl-ansi/rosetta-opf/pull/11

You can get Ipopt to print it if you turn up the output level.

**Comment by odow** [comment]
> You can get Ipopt to print it if you turn up the output level.

Actually, it's:
```julia
set_optimizer_attribute(model, "print_timing_statistics", "yes")
```

**Comment by ccoffrin** [comment]
Is there anything actionable to do on this topic?  As far as I can tell, we already collect as much of this as we can.

**Comment by odow** [comment]
Nah we can probably just close this
