### ISSUE TITLE
On Constraint Counting

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/rosetta-opf#9]
This could be a topic for standardization across the packages.  Key points,
- Do variable bounds count as constraints?
- Do double sided constraints count as one or two?

**Comment by odow** [comment]
- Do variable bounds count as constraints?

No. Constraints should mean that they appear as a row in the jacobian.
 
- Do double sided constraints count as one or two?

One. Only one row appears in the jacobian.

**Comment by ccoffrin** [comment]
Good point. Maybe the better common denominator is then, does each NL framework have an easy way to query the number of rows, columns and non-zeros in the model's Jacobian?

**Comment by odow** [comment]
Rows and columns are easy, but often trivial if you have to pass a vector of constraints and variable bounds. So not sure that's interesting to ask.

Non-zeros are more interesting. But that's tricky, because JuMP doesn't support querying the non-zeros in the linear/quadratic part of the Jacobins.

**Comment by odow** [comment]
This is being added to JuMP: https://github.com/jump-dev/JuMP.jl/pull/2936
